### ISSUE TITLE
Feature request: Add DateOnly Converter to Logging JsonSerializer

### ISSUE THREAD

**Issue by BradKnowles** [aws-powertools/powertools-lambda-dotnet#501]
### Use case

If the object being logged has a `DateOnly` property the Logging framework throws an exception.

`Serialization and deserialization of 'System.DateOnly' instances are not supported. The unsupported member type is located on type 'System.Nullable``1[System.DateOnly]'`

### Solution/User Experience

Ideally, the Logging framework would handle `DateOnly` fields without any additional or custom logic from application developers.

### Alternative solutions

At the moment, the workaround is to add a `[JsonConverter(typeof(DateOnlyJsonConverter))]` attribute to each property of the object being serialized, where `DateOnlyConverter` is a custom converter that is each of our applications.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (.NET) Tenets](https://docs.powertools.aws.dev/lambda/dotnet/tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by hjgraca** [comment]
Hi @BradKnowles , this is a .Net 6 limitation `System.Text.Json` source generator does not have built-in support for `DateOnly/TimeOnly` types, this was added to .NET 7. https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/#source-generation-improvements and https://github.com/dotnet/runtime/issues/53539.

This is an issue that will be present in other utilities like Tracing, due to the way XRay SDK does serialization. https://github.com/aws/aws-xray-sdk-dotnet/issues/212

We will discuss this internally to see if there is anything we can do to improve the experience. At the moment the solution is to create the converters.

**Comment by hjgraca** [comment]
cc: @amirkaws

**Comment by BradKnowles** [comment]
I was thinking it could be added like the `ByteArrayConverter` etc. was added in PR #152.

**Comment by hjgraca** [comment]
@BradKnowles we will be adding custom converter for DateOnly and TmeOnly. Thanks for raising the issue. We will be updating this issue with the progress.

**Comment by hjgraca** [comment]
@BradKnowles released in version 1.8.1 - Logging version 1.4.3.
Really appreciate opening this issue and the feedback.
